name: Docker image

on:
  push:
    branches: master

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get release version
        run: echo ::set-env name=RELEASE_VERSION::$(echo ${GITHUB_REF:10})
      - name: Set up Docker Buildx
        id: buildx-latest
        uses: crazy-max/ghaction-docker-buildx@v1
      - name: Build master
        env:
          DOCKER_USERNAME: 'qs5779'
          DOCKER_PASSWORD: '${{ secrets.DOCKER_ACCESS_TOKEN }}'
          PLATFORMS: "linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64"
        run: ./bin/wfbuild.sh -t wtfo/wtfapp --push
